name: WindSend Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: aarch64-unknown-linux-gnu

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libxdo-dev libappindicator3-dev 
          sudo apt-get install -y pkg-config libssl-dev build-essential linux-libc-dev
          sudo apt-get install -y musl-dev musl-tools
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Run Build Script
        env:
          AUTO_BUILD: true # for build script
        working-directory: ./
        # run: ./build.sh
        # generate test zip file
        run: |
          mkdir -p ./bin
          cat > ./bin/test.txt <<EOF
            Hello, World!
            EOF
          zip -r ./bin/test.zip ./bin/test.txt

      - name: Archive artifacts
        id: build_archive
        uses: actions/upload-artifact@v4
        with:
          name: WindSend-Archives
          path: ./bin/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: WindSend-Archives
          #   path: ./

      - name: List artifacts
        run: |
          ls -l
          ls -l ./WindSend-Archives

      - name: Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/') # e.g. refs/tags/v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./WindSend-Archives/*.zip
          tag_name: ${{ github.ref }}
          draft: true
