name: WindSend Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: aarch64-unknown-linux-gnu

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libxdo-dev libappindicator3-dev
          sudo apt-get install -y pkg-config libssl-dev build-essential linux-libc-dev
          sudo apt-get install -y musl-dev musl-tools
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Run Build Script
        env:
          CI_RUNNING: true # for build script
        working-directory: ./
        run: ./build.sh
        # generate test zip file
        # run: |
        #   mkdir -p ./bin
        #   echo "Hello, World!" > ./bin/test.txt
        #   zip -r ./bin/test.zip ./bin/test.txt
        #   echo "Hello, World!" > ./bin/test.apk

      - name: Archive artifacts
        id: build_archive
        uses: actions/upload-artifact@v4
        with:
          name: WindSend-Archives
          path: |
            ./bin/*.zip
            ./bin/*.apk
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: WindSend-Archives
          path: ./Downloaded-Archives

      - name: Echo env
        run: |
          echo 'ref ${{ github.ref }}'
          echo 'ref name ${{ github.ref_name }}'
          echo 'sha ${{ github.sha }}'
          echo 'actor ${{ github.actor }}'
          echo 'repository ${{ github.repository }}'
          echo 'repository_owner ${{ github.repository_owner }}'
          echo 'event_name ${{ github.event_name }}'
          echo 'event_path ${{ github.event_path }}'
          echo 'workspace ${{ github.workspace }}'
          echo 'action ${{ github.action }}'
          echo 'job ${{ github.job }}'
          echo 'run_id ${{ github.run_id }}'
          echo 'run_number ${{ github.run_number }}'

      - name: Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/') # e.g. refs/tags/v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./Downloaded-Archives/*.zip
            ./Downloaded-Archives/*.apk
          draft: true
