name: Rust Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Build ${{ matrix.os }}
        working-directory: ./windSend-rs
        run: cargo build --verbose

      - name: Run tests
        working-directory: ./windSend-rs
        run: cargo test --verbose

  build-aarch64-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build aarch64-pc-windows-msvc
        run: cargo build --target aarch64-pc-windows-msvc --verbose
      - name: Run tests
        run: cargo test --target aarch64-pc-windows-msvc --verbose
