name: Rust linux musl test

on:
  workflow_dispatch:

env:
  RUST_BACKTRACE: full
  CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        rust: [stable]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: x86_64-unknown-linux-musl
          rustflags: "-D warnings"

      - name: Install dependencies on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libxdo-dev libappindicator3-dev 
          sudo apt-get install -y pkg-config libssl-dev build-essential linux-libc-dev
          sudo apt-get install -y musl-dev musl-tools

      - name: Build ${{ matrix.os }}
        working-directory: ./windSend-rs
        run: cargo build --target x86_64-unknown-linux-musl --verbose

      - name: Run tests
        working-directory: ./windSend-rs
        run: cargo test --verbose
